### ISSUE TITLE
net error exception not catched

### ISSUE THREAD

**Issue by guojilong** [HotBitmapGG/CreditSesameRingView#1]
`617-4718/com.hotbitmapgg.rxzhihu E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-3
                                                                       Process: com.hotbitmapgg.rxzhihu, PID: 4617
                                                                       java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add`onError`handling.
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: rx.exceptions.OnErrorNotImplementedException: HTTP 504 Gateway Time-out
                                                                           at rx.Observable$27.onError(Observable.java:7923)
                                                                           at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
                                                                           at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
                                                                        Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 504 Gateway Time-out
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:163)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:158)
                                                                           at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:113)
                                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
                                                                           at rx.Observable$2.call(Observable.java:162)
                                                                           at rx.Observable$2.call(Observable.java:154)
                                                                           at rx.Observable$2.call(Observable.java:162)
                                                                           at rx.Observable$2.call(Observable.java:154)
                                                                           at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                           at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:818) `

**Comment by HotBitmapGG** [comment]
@guojilong 这个是另外一个项目的崩溃日志,这里先关了,我晚点看一下
